### ISSUE TITLE
visualization dialog causes chimeraX crashes when "Apply" clicked

### ISSUE THREAD

**Issue by heejongkim** [ScheltemaLab/ChimeraX_bundle#2]
Hi,

I just want to report a possible bug associated with visualization dialog.
When I set all the cut-off and styles, i can see that they are applied in realtime.
However, when i click Apply, then the entire chimeraX got crashed and entire software got killed.

I tested under macOS 11.7 and Ubuntu 18.04 LTS. The symptom is consistent across different platform with many different datasets.

If you need any further information for troubleshooting, please let me know. I will do my best to provide them.

Thank you.

p.s. the version I tested with is ChimeraX 1.4 with XMAS 1.1.2

**Comment by e-pettersen** [comment]
By "you", I mean the XMAS developers. :-)

**Comment by andzajan** [comment]
Thank you for a fix @michabirklbauer!
