### ISSUE TITLE
Specifications for evidence file

### ISSUE THREAD

**Issue by michabirklbauer** [ScheltemaLab/ChimeraX_bundle#3]
Greetings!

In your manual you are writing "XMAS currently supports evidence files generated with the search engines XlinkX for Proteome
Discoverer (PD), Xi, and pLink, in csv, tsv, txt, and xlsx format. Additionally, mzIdentML files (mzid format) are supported."

Are there any specifications for how an evidence file has to look like? E.g. which columns do have to be there etc.
I am asking this in regards to using XMAS also for other XL search engines

**Comment by andzajan** [comment]
Hi @michabirklbauer, sorry for delayed response. Preferred input would be mzIdentML, but you can also see what column names are required from **Table 1** from user manual [Chapter 7](https://github.com/ScheltemaLab/ChimeraX_bundle/blob/main/user_manual/XMAS_manual.md#7-managing-evidence-files).

**Comment by michabirklbauer** [comment]
Thanks a lot for the reply, I will try that out!
